//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.06 at 05:58:13 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gaurav.com/soap/example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gaurav.soap.example;
